//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "TencentPlayerFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface TencentPlayerFluttifyPlugin (SubHandler0)
- (NSDictionary<NSString*, Handler>*) getSubHandler0;
@end

NS_ASSUME_NONNULL_END
