//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "TencentPlayerFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface TencentPlayerFluttifyPlugin (SubHandler4)
- (NSDictionary<NSString*, Handler>*) getSubHandler4;
@end

NS_ASSUME_NONNULL_END
