name: tencent_player_fluttify
description: An `Tencent Player` Core Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.0.9
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.13.0-rc.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.tencent_player_fluttify
        pluginClass: TencentPlayerFluttifyPlugin
      ios:
        pluginClass: TencentPlayerFluttifyPlugin