//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "TencentPlayerFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface TencentPlayerFluttifyPlugin (SubHandlerCustom)
- (NSDictionary<NSString*, Handler>*) getSubHandlerCustom;
@end

NS_ASSUME_NONNULL_END
