// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:tencent_player_fluttify/src/android/android.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';


// type check
@optionalTypeArgs
Future<bool> TencentPlayerFluttifyAndroidIs<T>(dynamic __this__) async {
  final typeName = T.toString();
  if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ is T;
  }
  else if (T == com_tencent_rtmp_TXLog) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLog', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXAudioRawDataListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_ITXAudioRawDataListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ui_TXDashBoard) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ui_TXDashBoard', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ui_TXCloudVideoView) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ui_TXCloudVideoView', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ui_TXLogView) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ui_TXLogView', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ITXVodPlayListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ITXVodPlayListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_video_TXScreenCapture_TXScreenCaptureAssistantActivity) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_video_TXScreenCapture_TXScreenCaptureAssistantActivity', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_video_TXScreenCapture) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_video_TXScreenCapture', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLiveBase) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLiveBase', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXPlayInfoParams) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXPlayInfoParams', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_TXLiteAVTexture) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_TXLiteAVTexture', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXVodPlayer) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXVodPlayer', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXPlayerAuthBuilder) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXPlayerAuthBuilder', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ITXLivePlayListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ITXLivePlayListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_ITXVodPreloadListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_ITXVodPreloadListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_ITXVodDownloadListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_ITXVodDownloadListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadMediaInfo) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_TXVodDownloadMediaInfo', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadDataSource) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_TXVodDownloadDataSource', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_TXVodPreloadManager) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_TXVodPreloadManager', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadManager) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_downloader_TXVodDownloadManager', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLiveBaseListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLiveBaseListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLiveConstants) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLiveConstants', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXBitrateItem) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXBitrateItem', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_ITXLivePushListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_ITXLivePushListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXSnapshotListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_ITXSnapshotListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayConfig) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayConfig', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXPlayerGlobalSetting) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXPlayerGlobalSetting', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXVodPlayConfig) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXVodPlayConfig', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXAudioVolumeEvaluationListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_ITXAudioVolumeEvaluationListener', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXImageSprite) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXImageSprite', {'__this__': __this__});
    return result;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXVideoRawDataListener) {
    final result = await kTencentPlayerFluttifyChannel.invokeMethod('RefClass::isKindOfcom_tencent_rtmp_TXLivePlayer_ITXVideoRawDataListener', {'__this__': __this__});
    return result;
  }
  else {
    return false;
  }
}

// type cast
// 给一个可选的泛型, 如果没有指定泛型就返回dynamic
@optionalTypeArgs
T? TencentPlayerFluttifyAndroidAs<T>(dynamic __this__) {
  final typeName = T.toString();

  if (__this__ == null) {
    return null;
  } else if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ as T;
  }
  else if (T == com_tencent_rtmp_TXLog) {
    return (com_tencent_rtmp_TXLog()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXAudioRawDataListener) {
    return (com_tencent_rtmp_TXLivePlayer_ITXAudioRawDataListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ui_TXDashBoard) {
    return (com_tencent_rtmp_ui_TXDashBoard()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ui_TXCloudVideoView) {
    return (com_tencent_rtmp_ui_TXCloudVideoView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ui_TXLogView) {
    return (com_tencent_rtmp_ui_TXLogView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer) {
    return (com_tencent_rtmp_TXLivePlayer()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ITXVodPlayListener) {
    return (com_tencent_rtmp_ITXVodPlayListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_video_TXScreenCapture_TXScreenCaptureAssistantActivity) {
    return (com_tencent_rtmp_video_TXScreenCapture_TXScreenCaptureAssistantActivity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_video_TXScreenCapture) {
    return (com_tencent_rtmp_video_TXScreenCapture()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLiveBase) {
    return (com_tencent_rtmp_TXLiveBase()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXPlayInfoParams) {
    return (com_tencent_rtmp_TXPlayInfoParams()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_TXLiteAVTexture) {
    return (com_tencent_rtmp_TXLivePlayer_TXLiteAVTexture()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXVodPlayer) {
    return (com_tencent_rtmp_TXVodPlayer()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXPlayerAuthBuilder) {
    return (com_tencent_rtmp_TXPlayerAuthBuilder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener) {
    return (com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ITXLivePlayListener) {
    return (com_tencent_rtmp_ITXLivePlayListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_ITXVodPreloadListener) {
    return (com_tencent_rtmp_downloader_ITXVodPreloadListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_ITXVodDownloadListener) {
    return (com_tencent_rtmp_downloader_ITXVodDownloadListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadMediaInfo) {
    return (com_tencent_rtmp_downloader_TXVodDownloadMediaInfo()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadDataSource) {
    return (com_tencent_rtmp_downloader_TXVodDownloadDataSource()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_TXVodPreloadManager) {
    return (com_tencent_rtmp_downloader_TXVodPreloadManager()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_downloader_TXVodDownloadManager) {
    return (com_tencent_rtmp_downloader_TXVodDownloadManager()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLiveBaseListener) {
    return (com_tencent_rtmp_TXLiveBaseListener()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLiveConstants) {
    return (com_tencent_rtmp_TXLiveConstants()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXBitrateItem) {
    return (com_tencent_rtmp_TXBitrateItem()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_ITXLivePushListener) {
    return (com_tencent_rtmp_ITXLivePushListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXSnapshotListener) {
    return (com_tencent_rtmp_TXLivePlayer_ITXSnapshotListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayConfig) {
    return (com_tencent_rtmp_TXLivePlayConfig()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXPlayerGlobalSetting) {
    return (com_tencent_rtmp_TXPlayerGlobalSetting()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXVodPlayConfig) {
    return (com_tencent_rtmp_TXVodPlayConfig()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXAudioVolumeEvaluationListener) {
    return (com_tencent_rtmp_TXLivePlayer_ITXAudioVolumeEvaluationListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXImageSprite) {
    return (com_tencent_rtmp_TXImageSprite()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_tencent_rtmp_TXLivePlayer_ITXVideoRawDataListener) {
    return (com_tencent_rtmp_TXLivePlayer_ITXVideoRawDataListener.subInstance()..refId = (__this__ as Ref).refId) as T;
  }

  final FoundationFluttifyObject = FoundationFluttifyAndroidAs<T>(__this__);
  if (FoundationFluttifyObject != null) {
    return FoundationFluttifyObject;
  }

  // 匹配不到目标类型, 直接返回原对象
  debugPrint('匹配不到目标类型, 直接返回原对象');
  return __this__;
}