// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum TX_Enum_MediaType {
  MEDIA_TYPE_AUTO /* 0 */,
  MEDIA_TYPE_HLS_VOD /* 1 */,
  MEDIA_TYPE_HLS_LIVE /* 2 */
}

extension TX_Enum_MediaTypeToX on TX_Enum_MediaType {
  int toValue() {
    switch (this) {
      case TX_Enum_MediaType.MEDIA_TYPE_AUTO: return 0;
      case TX_Enum_MediaType.MEDIA_TYPE_HLS_VOD: return 1;
      case TX_Enum_MediaType.MEDIA_TYPE_HLS_LIVE: return 2;
      default: return 0;
    }
  }
}

extension TX_Enum_MediaTypeFromX on int {
  TX_Enum_MediaType toTX_Enum_MediaType() {
    switch (this) {
      case 0: return TX_Enum_MediaType.MEDIA_TYPE_AUTO;
      case 1: return TX_Enum_MediaType.MEDIA_TYPE_HLS_VOD;
      case 2: return TX_Enum_MediaType.MEDIA_TYPE_HLS_LIVE;
      default: return TX_Enum_MediaType.values[this + 0];
    }
  }
}