// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum TXRecordResultCode {
  RECORD_RESULT_OK /* 0 */,
  RECORD_RESULT_OK_INTERRUPT /* 1 */,
  RECORD_RESULT_FAILED /* 1001 */
}

extension TXRecordResultCodeToX on TXRecordResultCode {
  int toValue() {
    switch (this) {
      case TXRecordResultCode.RECORD_RESULT_OK: return 0;
      case TXRecordResultCode.RECORD_RESULT_OK_INTERRUPT: return 1;
      case TXRecordResultCode.RECORD_RESULT_FAILED: return 1001;
      default: return 0;
    }
  }
}

extension TXRecordResultCodeFromX on int {
  TXRecordResultCode toTXRecordResultCode() {
    switch (this) {
      case 0: return TXRecordResultCode.RECORD_RESULT_OK;
      case 1: return TXRecordResultCode.RECORD_RESULT_OK_INTERRUPT;
      case 1001: return TXRecordResultCode.RECORD_RESULT_FAILED;
      default: return TXRecordResultCode.values[this + 0];
    }
  }
}