// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum TXRecordType {
  RECORD_TYPE_STREAM_SOURCE /* 1 */
}

extension TXRecordTypeToX on TXRecordType {
  int toValue() {
    switch (this) {
      case TXRecordType.RECORD_TYPE_STREAM_SOURCE: return 1;
      default: return 0;
    }
  }
}

extension TXRecordTypeFromX on int {
  TXRecordType toTXRecordType() {
    switch (this) {
      case 1: return TXRecordType.RECORD_TYPE_STREAM_SOURCE;
      default: return TXRecordType.values[this + 1];
    }
  }
}