// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum V2TXAudioRoute {
  V2TXAudioModeSpeakerphone /* null */,
  V2TXAudioModeEarpiece /* null */
}

extension V2TXAudioRouteToX on V2TXAudioRoute {
  int toValue() {
    switch (this) {
      case V2TXAudioRoute.V2TXAudioModeSpeakerphone: return V2TXAudioRoute.V2TXAudioModeSpeakerphone.index + 0;
      case V2TXAudioRoute.V2TXAudioModeEarpiece: return V2TXAudioRoute.V2TXAudioModeEarpiece.index + 0;
      default: return 0;
    }
  }
}

extension V2TXAudioRouteFromX on int {
  V2TXAudioRoute toV2TXAudioRoute() {
    switch (this) {
      
      default: return V2TXAudioRoute.values[this + 0];
    }
  }
}