// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum V2TXLiveRotation {
  V2TXLiveRotation0 /* null */,
  V2TXLiveRotation90 /* null */,
  V2TXLiveRotation180 /* null */,
  V2TXLiveRotation270 /* null */
}

extension V2TXLiveRotationToX on V2TXLiveRotation {
  int toValue() {
    switch (this) {
      case V2TXLiveRotation.V2TXLiveRotation0: return V2TXLiveRotation.V2TXLiveRotation0.index + 0;
      case V2TXLiveRotation.V2TXLiveRotation90: return V2TXLiveRotation.V2TXLiveRotation90.index + 0;
      case V2TXLiveRotation.V2TXLiveRotation180: return V2TXLiveRotation.V2TXLiveRotation180.index + 0;
      case V2TXLiveRotation.V2TXLiveRotation270: return V2TXLiveRotation.V2TXLiveRotation270.index + 0;
      default: return 0;
    }
  }
}

extension V2TXLiveRotationFromX on int {
  V2TXLiveRotation toV2TXLiveRotation() {
    switch (this) {
      
      default: return V2TXLiveRotation.values[this + 0];
    }
  }
}