// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum V2TXLiveAudioQuality {
  V2TXLiveAudioQualitySpeech /* null */,
  V2TXLiveAudioQualityDefault /* null */,
  V2TXLiveAudioQualityMusic /* null */
}

extension V2TXLiveAudioQualityToX on V2TXLiveAudioQuality {
  int toValue() {
    switch (this) {
      case V2TXLiveAudioQuality.V2TXLiveAudioQualitySpeech: return V2TXLiveAudioQuality.V2TXLiveAudioQualitySpeech.index + 0;
      case V2TXLiveAudioQuality.V2TXLiveAudioQualityDefault: return V2TXLiveAudioQuality.V2TXLiveAudioQualityDefault.index + 0;
      case V2TXLiveAudioQuality.V2TXLiveAudioQualityMusic: return V2TXLiveAudioQuality.V2TXLiveAudioQualityMusic.index + 0;
      default: return 0;
    }
  }
}

extension V2TXLiveAudioQualityFromX on int {
  V2TXLiveAudioQuality toV2TXLiveAudioQuality() {
    switch (this) {
      
      default: return V2TXLiveAudioQuality.values[this + 0];
    }
  }
}