// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tencent_player_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class com_tencent_rtmp_TXLiveConstants extends java_lang_Object  {
  //region constants
  static const String name__ = 'com.tencent.rtmp.TXLiveConstants';

  @override
  final String tag__ = 'tencent_player_fluttify';

  static final int VIDEO_RESOLUTION_TYPE_360_640 = 0;
  static final int VIDEO_RESOLUTION_TYPE_540_960 = 1;
  static final int VIDEO_RESOLUTION_TYPE_720_1280 = 2;
  static final int VIDEO_RESOLUTION_TYPE_640_360 = 3;
  static final int VIDEO_RESOLUTION_TYPE_960_540 = 4;
  static final int VIDEO_RESOLUTION_TYPE_1280_720 = 5;
  static final int VIDEO_RESOLUTION_TYPE_320_480 = 6;
  static final int VIDEO_RESOLUTION_TYPE_180_320 = 7;
  static final int VIDEO_RESOLUTION_TYPE_270_480 = 8;
  static final int VIDEO_RESOLUTION_TYPE_320_180 = 9;
  static final int VIDEO_RESOLUTION_TYPE_480_270 = 10;
  static final int VIDEO_RESOLUTION_TYPE_240_320 = 11;
  static final int VIDEO_RESOLUTION_TYPE_360_480 = 12;
  static final int VIDEO_RESOLUTION_TYPE_480_640 = 13;
  static final int VIDEO_RESOLUTION_TYPE_320_240 = 14;
  static final int VIDEO_RESOLUTION_TYPE_480_360 = 15;
  static final int VIDEO_RESOLUTION_TYPE_640_480 = 16;
  static final int VIDEO_RESOLUTION_TYPE_480_480 = 17;
  static final int VIDEO_RESOLUTION_TYPE_270_270 = 18;
  static final int VIDEO_RESOLUTION_TYPE_160_160 = 19;
  static final int VIDEO_RESOLUTION_TYPE_1080_1920 = 30;
  static final int VIDEO_RESOLUTION_TYPE_1920_1080 = 31;
  static final int VIDEO_QUALITY_STANDARD_DEFINITION = 1;
  static final int VIDEO_QUALITY_HIGH_DEFINITION = 2;
  static final int VIDEO_QUALITY_SUPER_DEFINITION = 3;
  static final int VIDEO_QUALITY_LINKMIC_MAIN_PUBLISHER = 4;
  static final int VIDEO_QUALITY_LINKMIC_SUB_PUBLISHER = 5;
  static final int VIDEO_QUALITY_REALTIEM_VIDEOCHAT = 6;
  static final int VIDEO_QUALITY_ULTRA_DEFINITION = 7;
  static final int VIDEO_ANGLE_HOME_RIGHT = 0;
  static final int VIDEO_ANGLE_HOME_DOWN = 1;
  static final int VIDEO_ANGLE_HOME_LEFT = 2;
  static final int VIDEO_ANGLE_HOME_UP = 3;
  static final int CUSTOM_MODE_AUDIO_CAPTURE = 1;
  static final int CUSTOM_MODE_VIDEO_CAPTURE = 2;
  static final int CUSTOM_MODE_AUDIO_PREPROCESS = 4;
  static final int CUSTOM_MODE_VIDEO_PREPROCESS = 8;
  static final int RENDER_MODE_FULL_FILL_SCREEN = 0;
  static final int RENDER_MODE_ADJUST_RESOLUTION = 1;
  static final int RENDER_ROTATION_PORTRAIT = 0;
  static final int RENDER_ROTATION_LANDSCAPE = 270;
  static final int RENDER_ROTATION_0 = 0;
  static final int RENDER_ROTATION_90 = 90;
  static final int RENDER_ROTATION_180 = 180;
  static final int RENDER_ROTATION_270 = 270;
  static final int LOCAL_VIDEO_MIRROR_TYPE_AUTO = 0;
  static final int LOCAL_VIDEO_MIRROR_TYPE_ENABLE = 1;
  static final int LOCAL_VIDEO_MIRROR_TYPE_DISABLE = 2;
  static final int AUTO_ADJUST_NONE = -1;
  static final int AUTO_ADJUST_LIVEPUSH_STRATEGY = 0;
  static final int AUTO_ADJUST_LIVEPUSH_RESOLUTION_STRATEGY = 1;
  static final int AUTO_ADJUST_REALTIME_VIDEOCHAT_STRATEGY = 5;
  static final int AUTO_ADJUST_BITRATE_STRATEGY_1 = 0;
  static final int AUTO_ADJUST_BITRATE_RESOLUTION_STRATEGY_1 = 1;
  static final int AUTO_ADJUST_BITRATE_STRATEGY_2 = 2;
  static final int AUTO_ADJUST_BITRATE_RESOLUTION_STRATEGY_2 = 3;
  static final int AUTO_ADJUST_REALTIME_BITRATE_STRATEGY = 4;
  static final int AUTO_ADJUST_REALTIME_BITRATE_RESOLUTION_STRATEGY = 5;
  static final int PUSH_EVT_CONNECT_SUCC = 1001;
  static final int PUSH_EVT_PUSH_BEGIN = 1002;
  static final int PUSH_EVT_OPEN_CAMERA_SUCC = 1003;
  static final int PUSH_EVT_SCREEN_CAPTURE_SUCC = 1004;
  static final int PUSH_EVT_CHANGE_RESOLUTION = 1005;
  static final int PUSH_EVT_CHANGE_BITRATE = 1006;
  static final int PUSH_EVT_FIRST_FRAME_AVAILABLE = 1007;
  static final int PUSH_EVT_START_VIDEO_ENCODER = 1008;
  static final int PUSH_EVT_ROOM_IN = 1018;
  static final int PUSH_EVT_ROOM_IN_FAILED = 1022;
  static final int PUSH_EVT_ROOM_OUT = 1019;
  static final int PUSH_EVT_ROOM_USERLIST = 1020;
  static final int PUSH_EVT_ROOM_NEED_REENTER = 1021;
  static final int PUSH_EVT_ROOM_USER_ENTER = 1031;
  static final int PUSH_EVT_ROOM_USER_EXIT = 1032;
  static final int PUSH_EVT_ROOM_USER_VIDEO_STATE = 1033;
  static final int PUSH_EVT_ROOM_USER_AUDIO_STATE = 1034;
  static final int PUSH_ERR_OPEN_CAMERA_FAIL = -1301;
  static final int PUSH_ERR_OPEN_MIC_FAIL = -1302;
  static final int PUSH_ERR_VIDEO_ENCODE_FAIL = -1303;
  static final int PUSH_ERR_AUDIO_ENCODE_FAIL = -1304;
  static final int PUSH_ERR_UNSUPPORTED_RESOLUTION = -1305;
  static final int PUSH_ERR_UNSUPPORTED_SAMPLERATE = -1306;
  static final int PUSH_ERR_NET_DISCONNECT = -1307;
  static final int PUSH_ERR_SCREEN_CAPTURE_START_FAILED = -1308;
  static final int PUSH_ERR_SCREEN_CAPTURE_UNSURPORT = -1309;
  static final int PUSH_ERR_SCREEN_CAPTURE_DISTURBED = -1310;
  static final int PUSH_ERR_MIC_RECORD_FAIL = -1311;
  static final int PUSH_ERR_SCREEN_CAPTURE_SWITCH_DISPLAY_FAILED = -1312;
  static final int PUSH_ERR_INVALID_ADDRESS = -1313;
  static final int PUSH_WARNING_NET_BUSY = 1101;
  static final int PUSH_WARNING_RECONNECT = 1102;
  static final int PUSH_WARNING_HW_ACCELERATION_FAIL = 1103;
  static final int PUSH_WARNING_VIDEO_ENCODE_FAIL = 1104;
  static final int PUSH_WARNING_BEAUTYSURFACE_VIEW_INIT_FAIL = 1105;
  static final int PUSH_WARNING_VIDEO_ENCODE_BITRATE_OVERFLOW = 1106;
  static final int PUSH_WARNING_VIDEO_ENCODE_SW_SWITCH_HW = 1107;
  static final int PUSH_WARNING_DNS_FAIL = 3001;
  static final int PUSH_WARNING_SEVER_CONN_FAIL = 3002;
  static final int PUSH_WARNING_SHAKE_FAIL = 3003;
  static final int PUSH_WARNING_SERVER_DISCONNECT = 3004;
  static final int PUSH_WARNING_READ_WRITE_FAIL = 3005;
  static final int PUSH_WARNING_VIDEO_RENDER_FAIL = 2110;
  static final int PUSH_WARNING_MICROPHONE_DEVICE_ABNORMAL = 1204;
  static final int PUSH_WARNING_HEVC_ENCODE_NOT_SUPPORT = -2311;
  static final int PLAY_EVT_CONNECT_SUCC = 2001;
  static final int PLAY_EVT_RTMP_STREAM_BEGIN = 2002;
  static final int PLAY_EVT_RCV_FIRST_I_FRAME = 2003;
  static final int PLAY_EVT_RCV_FIRST_AUDIO_FRAME = 2026;
  static final int PLAY_EVT_PLAY_BEGIN = 2004;
  static final int PLAY_EVT_PLAY_PROGRESS = 2005;
  static final int PLAY_EVT_PLAY_END = 2006;
  static final int PLAY_EVT_PLAY_LOADING = 2007;
  static final int PLAY_EVT_START_VIDEO_DECODER = 2008;
  static final int PLAY_EVT_CHANGE_RESOLUTION = 2009;
  static final int PLAY_EVT_GET_PLAYINFO_SUCC = 2010;
  static final int PLAY_EVT_CHANGE_ROTATION = 2011;
  static final int PLAY_EVT_GET_MESSAGE = 2012;
  static final int PLAY_EVT_VOD_PLAY_PREPARED = 2013;
  static final int PLAY_EVT_VOD_LOADING_END = 2014;
  static final int PLAY_EVT_STREAM_SWITCH_SUCC = 2015;
  static final int PLAY_EVT_GET_METADATA = 2028;
  static final int PLAY_EVT_GET_FLVSESSIONKEY = 2031;
  static final int PLAY_ERR_NET_DISCONNECT = -2301;
  static final int PLAY_ERR_GET_RTMP_ACC_URL_FAIL = -2302;
  static final int PLAY_ERR_FILE_NOT_FOUND = -2303;
  static final int PLAY_ERR_HEVC_DECODE_FAIL = -2304;
  static final int PLAY_ERR_HLS_KEY = -2305;
  static final int PLAY_ERR_GET_PLAYINFO_FAIL = -2306;
  static final int PLAY_ERR_STREAM_SWITCH_FAIL = -2307;
  static final int PLAY_WARNING_VIDEO_DECODE_FAIL = 2101;
  static final int PLAY_WARNING_AUDIO_DECODE_FAIL = 2102;
  static final int PLAY_WARNING_RECONNECT = 2103;
  static final int PLAY_WARNING_RECV_DATA_LAG = 2104;
  static final int PLAY_WARNING_VIDEO_PLAY_LAG = 2105;
  static final int PLAY_WARNING_HW_ACCELERATION_FAIL = 2106;
  static final int PLAY_WARNING_VIDEO_DISCONTINUITY = 2107;
  static final int PLAY_WARNING_FIRST_IDR_HW_DECODE_FAIL = 2108;
  static final int PLAY_WARNING_DNS_FAIL = 3001;
  static final int PLAY_WARNING_SEVER_CONN_FAIL = 3002;
  static final int PLAY_WARNING_SHAKE_FAIL = 3003;
  static final int PLAY_WARNING_READ_WRITE_FAIL = 3005;
  static final int PLAY_WARNING_SPEAKER_DEVICE_ABNORMAL = 1205;
  static final int LOG_LEVEL_VERBOSE = 0;
  static final int LOG_LEVEL_DEBUG = 1;
  static final int LOG_LEVEL_INFO = 2;
  static final int LOG_LEVEL_WARN = 3;
  static final int LOG_LEVEL_ERROR = 4;
  static final int LOG_LEVEL_FATAL = 5;
  static final int LOG_LEVEL_NULL = 6;
  static final String EVT_UTC_TIME = "EVT_UTC_TIME";
  static final String EVT_BLOCK_DURATION = "EVT_BLOCK_DURATION";
  static final String EVT_TIME = "EVT_TIME";
  static final String EVT_DESCRIPTION = "EVT_MSG";
  static final String EVT_PARAM1 = "EVT_PARAM1";
  static final String EVT_PARAM2 = "EVT_PARAM2";
  static final String EVT_GET_MSG = "EVT_GET_MSG";
  static final String EVT_PLAY_COVER_URL = "EVT_PLAY_COVER_URL";
  static final String EVT_PLAY_URL = "EVT_PLAY_URL";
  static final String EVT_PLAY_NAME = "EVT_PLAY_NAME";
  static final String EVT_PLAY_DESCRIPTION = "EVT_PLAY_DESCRIPTION";
  static final String EVT_PLAY_PROGRESS_MS = "EVT_PLAY_PROGRESS_MS";
  static final String EVT_PLAY_DURATION_MS = "EVT_PLAY_DURATION_MS";
  static final String EVT_PLAY_PROGRESS = "EVT_PLAY_PROGRESS";
  static final String EVT_PLAY_DURATION = "EVT_PLAY_DURATION";
  static final String EVT_PLAYABLE_DURATION_MS = "EVT_PLAYABLE_DURATION_MS";
  static final String EVT_PLAYABLE_RATE = "EVT_PLAYABLE_RATE";
  static final String NET_STATUS_CPU_USAGE = "CPU_USAGE";
  static final String NET_STATUS_VIDEO_WIDTH = "VIDEO_WIDTH";
  static final String NET_STATUS_VIDEO_HEIGHT = "VIDEO_HEIGHT";
  static final String NET_STATUS_VIDEO_FPS = "VIDEO_FPS";
  static final String NET_STATUS_VIDEO_GOP = "VIDEO_GOP";
  static final String NET_STATUS_VIDEO_BITRATE = "VIDEO_BITRATE";
  static final String NET_STATUS_AUDIO_BITRATE = "AUDIO_BITRATE";
  static final String NET_STATUS_NET_SPEED = "NET_SPEED";
  static final String NET_STATUS_AUDIO_CACHE = "AUDIO_CACHE";
  static final String NET_STATUS_VIDEO_CACHE = "VIDEO_CACHE";
  static final String NET_STATUS_AUDIO_DROP = "AUDIO_DROP";
  static final String NET_STATUS_VIDEO_DROP = "VIDEO_DROP";
  static final String NET_STATUS_V_SUM_CACHE_SIZE = "V_SUM_CACHE_SIZE";
  static final String NET_STATUS_V_DEC_CACHE_SIZE = "V_DEC_CACHE_SIZE";
  static final String NET_STATUS_AV_PLAY_INTERVAL = "AV_PLAY_INTERVAL";
  static final String NET_STATUS_AV_RECV_INTERVAL = "AV_RECV_INTERVAL";
  static final String NET_STATUS_AUDIO_CACHE_THRESHOLD = "AUDIO_CACHE_THRESHOLD";
  static final String NET_STATUS_AUDIO_BLOCK_TIME = "AUDIO_BLOCK_TIME";
  static final String NET_STATUS_AUDIO_INFO = "AUDIO_PLAY_INFO";
  static final String NET_STATUS_NET_JITTER = "NET_JITTER";
  static final String NET_STATUS_SERVER_IP = "SERVER_IP";
  static final String NET_STATUS_VIDEO_DPS = "VIDEO_DPS";
  static final String NET_STATUS_QUALITY_LEVEL = "NET_QUALITY_LEVEL";
  static final int PAUSE_FLAG_PAUSE_VIDEO = 1;
  static final int PAUSE_FLAG_PAUSE_AUDIO = 2;
  static final String TXRTMPSDK_PUSHEVENT_SOURCE_OPENCAMERA = "TXRTMPSDK_PUSHEVENT_SOURCE_OPENCAMERA";
  static final String TXRTMPSDK_PUSHEVENT_SOURCE_OPENMIC = "TXRTMPSDK_PUSHEVENT_SOURCE_OPENMIC";
  static final String TXRTMPSDK_VIDEO_YUVSOURCE_LOCALCAMERA = "TXRTMPSDK_VIDEO_YUVSOURCE_LOCALCAMERA";
  static final String TXRTMPSDK_AUDIO_PCMSOURCE_LOCALMERGER = "TXRTMPSDK_AUDIO_PCMSOURCE_LOCALMERGER";
  static final int REVERB_TYPE_0 = 0;
  static final int REVERB_TYPE_1 = 1;
  static final int REVERB_TYPE_2 = 2;
  static final int REVERB_TYPE_3 = 3;
  static final int REVERB_TYPE_4 = 4;
  static final int REVERB_TYPE_5 = 5;
  static final int REVERB_TYPE_6 = 6;
  static final int VOICECHANGER_TYPE_0 = 0;
  static final int VOICECHANGER_TYPE_1 = 1;
  static final int VOICECHANGER_TYPE_2 = 2;
  static final int VOICECHANGER_TYPE_3 = 3;
  static final int VOICECHANGER_TYPE_4 = 4;
  static final int VOICECHANGER_TYPE_5 = 5;
  static final int VOICECHANGER_TYPE_6 = 6;
  static final int VOICECHANGER_TYPE_7 = 7;
  static final int VOICECHANGER_TYPE_8 = 8;
  static final int VOICECHANGER_TYPE_9 = 9;
  static final int VOICECHANGER_TYPE_10 = 10;
  static final int VOICECHANGER_TYPE_11 = 11;
  static final int ENCODE_VIDEO_SOFTWARE = 0;
  static final int ENCODE_VIDEO_HARDWARE = 1;
  static final int ENCODE_VIDEO_AUTO = 2;
  static final int RTMP_CHANNEL_TYPE_AUTO = 0;
  static final int RTMP_CHANNEL_TYPE_STANDARD = 1;
  static final int RTMP_CHANNEL_TYPE_PRIVATE = 2;
  static final int BEAUTY_STYLE_SMOOTH = 0;
  static final int BEAUTY_STYLE_NATURE = 1;
  static final int BEAUTY_STYLE_PITU = 2;
  static final int BEAUTY_STYLE_HAZY = 3;
  static final int AUDIO_ROUTE_SPEAKER = 0;
  static final int AUDIO_ROUTE_RECEIVER = 1;
  static final int AUDIO_VOLUME_TYPE_AUTO = 0;
  static final int AUDIO_VOLUME_TYPE_MEDIA = 1;
  static final int AUDIO_VOLUME_TYPE_VOIP = 2;
  static final int VIDEO_RESOLUTION_720X1280 = 921600;
  static final int VIDEO_RESOLUTION_1080X1920 = 2073600;
  static final int VIDEO_RESOLUTION_1440X2560 = 3686400;
  static final int VIDEO_RESOLUTION_2160X3840 = 8294400;
  //endregion

  //region creators
  static Future<com_tencent_rtmp_TXLiveConstants> create__() async {
    final __result__ = await kTencentPlayerFluttifyChannel.invokeMethod(
      'ObjectFactory::createcom_tencent_rtmp_TXLiveConstants__',
    
    );
    return TencentPlayerFluttifyAndroidAs<com_tencent_rtmp_TXLiveConstants>(__result__)!;
  }
  
  static Future<List<com_tencent_rtmp_TXLiveConstants>> create_batch__(int length) async {
    assert(true);
    final __result_batch__ = await  kTencentPlayerFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchcom_tencent_rtmp_TXLiveConstants__',
      {'length': length}
    );
    return __result_batch__
        ?.map((it) => TencentPlayerFluttifyAndroidAs<com_tencent_rtmp_TXLiveConstants>(it))
        .where((element) => element !=null)
        .cast<com_tencent_rtmp_TXLiveConstants>()
        .toList() ?? <com_tencent_rtmp_TXLiveConstants>[];
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'com_tencent_rtmp_TXLiveConstants{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension com_tencent_rtmp_TXLiveConstants_Batch on List<com_tencent_rtmp_TXLiveConstants?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}