//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import <TXLiteAVSDK_Player/TXLiteAVSDK.h>

@protocol FlutterPluginRegistrar;

NS_ASSUME_NONNULL_BEGIN

@interface V2TXLivePlayer_Anonymous : NSObject<V2TXLivePlayer>

- (instancetype) initWithFlutterPluginRegistrar: (NSObject <FlutterPluginRegistrar> *) registrar;

@property(nonatomic) NSObject<FlutterPluginRegistrar>* registrar;

@end

NS_ASSUME_NONNULL_END

