// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:tencent_player_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';



mixin com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener on java_lang_Object {
  

  

  static Future<com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener> anonymous__({void Function(com_tencent_rtmp_TXLivePlayer_TXLiteAVTexture? var1)? onRenderVideoFrame}) async {
    final __result__ = await kTencentPlayerFluttifyChannel.invokeMethod('com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener::createAnonymous__');
  
    final __object__ = TencentPlayerFluttifyAndroidAs<com_tencent_rtmp_TXLivePlayer_ITXLivePlayVideoRenderListener>(__result__)!;
  
    // handle callback
    MethodChannel('com.tencent.rtmp.TXLivePlayer.ITXLivePlayVideoRenderListener::Callback@${__object__.refId}', kTencentPlayerFluttifyMethodCodec)
        .setMethodCallHandler((methodCall) async {
          try {
            final args = methodCall.arguments as Map;
            switch (methodCall.method) {
              case 'Callback::onRenderVideoFrame::onRenderVideoFrame':
                // print log
                if (fluttifyLogEnabled) {
            
                }
            
                // handle the native call
                onRenderVideoFrame?.call(TencentPlayerFluttifyAndroidAs(args['var1']));
                break;
              default:
                throw MissingPluginException('方法${methodCall.method}未实现');
                break;
            }
          } catch (e) {
            debugPrint(e.toString());
            rethrow;
          }
        });
  
    return __object__;
  }
  

  @override
  final String tag__ = 'tencent_player_fluttify';

  

  

  /* @mustCallSuper */
  Future<void> onRenderVideoFrame(com_tencent_rtmp_TXLivePlayer_TXLiteAVTexture var1) async {}
  
}

